version: 0.2

phases:
  install:
    commands:
      - echo "Testing Internet Access"
      - curl -I https://google.com || echo "NO INTERNET"
      - echo "Installing dependencies on Amazon Linux"
      - sudo yum update -y
      - sudo yum install -y unzip git curl
  pre_build:
    commands:
      - echo "Pre-build step"
  build:
    commands:
      - echo "Build step"
  post_build:
    commands:
      - echo "Post-build step"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
