version: 0.2

phases:
  install:
    commands:
      - echo Using built-in PHP and Composer from AWS CodeBuild image...
      - php -v
      - composer --version
      - composer install

  pre_build:
    commands:
      - echo Pre-build phase...
      - composer dump-autoload

  build:
    commands:
      - echo Build phase...

  post_build:
    commands:
      - echo ✅ Build completed successfully.

artifacts:
  files:
    - '**/*'
  discard-paths: yes
