version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo Installing dependencies on Amazon Linux 2...
      - yum update -y
      - amazon-linux-extras enable php8.2
      - yum clean metadata
      - yum install -y php php-mbstring php-xml php-json git unzip curl
      - echo Installing Composer...
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - echo Installing PHP project dependencies with Composer...
      - composer install

  pre_build:
    commands:
      - echo Running pre-build steps...
      - composer dump-autoload

  build:
    commands:
      - echo Running build steps...

  post_build:
    commands:
      - echo ✅ Build and post-build steps completed.

artifacts:
  files:
    - '**/*'
  discard-paths: yes
